---
layout: cv
title: Esther Scott's CV
---
# Isaac Newton
student, not expert- just here trying to figure out what im doing.

<div id="https://github.com/okestherrr/DS250Repository">
<a href="scottes@byui.edu">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My Instagram page</a>
</div>


## Currently

I am a student in Brother Lewis class, I am here because I want to learn about how to program in pandas. Idk what i was doing for 1/16th of the time but luckily he was there to help me and also to get confused too. 

### Specialized in

Laws of motion, gravitation, minting coins, disliking [Robert Hooke](http://en.wikipedia.org/wiki/Robert_Hooke)


### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.


## Education

`1654-1660`
__The King's School, Grantham.__

`June 1661 - now`
__Trinity College, Cambridge__

- Sizar

`1667 - death`
__Trinity College, Cambridge__

- Fellow



## Awards

`2012`
President, *Royal Society*, London, UK

Associate, *French Academy of Science*, Paris, France



## Publications

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001


## Occupation

`1600`
__Royal Mint__, London

- Warden
- Minted coins

`1600`
__Lucasian professor of Mathematics__, Cambridge University



<!-- ### Footer

Last updated: May 2013 -->